module.exports = {
    DEPOSIT_UPDATE: 'DEPOSIT_UPDATE',
    WITHDRAW_UPDATE: 'WITHDRAW_UPDATE',
    BALANCE_UPDATE: 'BALANCE_UPDATE',
    ORDER_CREATE: 'ORDER_CREATE',
    ORDER_UPDATE: 'ORDER_UPDATE',
    ORDER_CANCEL: 'ORDER_CANCEL',
    ETHER_PRICE: 'ETHER_PRICE',
    ORDER_HISTORY_CREATE: 'ORDER_HISTORY_CREATE',
};
